name: Auto Green Contribution

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "*/10 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Modify last update
        run: |
          d='DATE '`date '+%Y-%m-%d %H:%M:%S'`
          echo $d > LOG.md
          
      - name: Commit and Push
        run: | 
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add LOG.md
          
          messages=("Update activity log" "Update contribution" "Update timestamp" "Refresh stats" "Update status" "Daily update" "Regular update" "Routine update" "Update log file" "Maintain activity")
          
          rand=$((RANDOM % 10))
          message=${messages[$rand]}
          
          git commit -m "$message"
          git push
